### ISSUE TITLE
When Hiding MiniMap The Border doesn't hide

### ISSUE THREAD

**Issue by Drukhi** [blooblahguy/bdNameplates#3]
Hello sir,

and first thank you for your bdAddons - i like them a lot.

With bdMinimap, there is an issue since ... if i hide the minimap with the binded button, the minimap hides, but the border doesn't. So it would be nice if this can be fixed in a future update.

This would keep the UI more clean. :) Thx a lot mate!

Best regard,
Drukhi

**Comment by Drukhi** [comment]
here is a screenshot:
![wowscrnshot_072418_145321](https://user-images.githubusercontent.com/41521167/43139175-5fe13956-8f51-11e8-8fbd-c9d5283423df.jpg)

**Comment by gladelynch** [comment]
This will be fixed in todays update, sorry for the slow reply!
